import { useMemo, useState } from 'react'
import { AreaChart,Area,CartesianGrid,XAxis,YAxis,Tooltip,ResponsiveContainer,Line,ComposedChart,Bar,Legend } from 'recharts'
import { Zap, Gauge, Wallet, TrendingDown, TrendingUp, Plus, CalendarDays, Target } from 'lucide-react'
import { brl,num,monthLabel,monthLong } from '../utils/format'

function collectSeries(bills){
 const map=new Map()
 bills.forEach(b=>{(b.historico_consumo||[]).forEach(h=>{if(h?.mes&&h?.kwh!=null)map.set(h.mes,{mes:h.mes,kwh:Number(h.kwh),demanda:null,valor:null})});if(b.mes_referencia){const p=map.get(b.mes_referencia)||{mes:b.mes_referencia,kwh:null,demanda:null,valor:null};if(b.consumo_kwh!=null)p.kwh=Number(b.consumo_kwh);if(b.demanda_kw!=null)p.demanda=Number(b.demanda_kw);if(b.valor_total!=null)p.valor=Number(b.valor_total);map.set(b.mes_referencia,p)}})
 return [...map.values()].sort((a,b)=>a.mes.localeCompare(b.mes))
}
export default function DashboardPage({bills,onAdd}){
 const series=useMemo(()=>collectSeries(bills),[bills]); const years=[...new Set(series.map(x=>x.mes?.slice(0,4)).filter(Boolean))].sort().reverse(); const [mode,setMode]=useState('mensal'); const [year,setYear]=useState(years[0]||new Date().getFullYear().toString()); const months=series.filter(x=>x.mes?.startsWith(year)); const [month,setMonth]=useState(months.at(-1)?.mes||'')
 const current= mode==='mensal' ? (bills.find(b=>b.mes_referencia===month)||bills[0]) : null
 const yearBills=bills.filter(b=>b.mes_referencia?.startsWith(year)); const totalKwh=mode==='anual'?yearBills.reduce((s,b)=>s+(Number(b.consumo_kwh)||0),0):current?.consumo_kwh; const totalValue=mode==='anual'?yearBills.reduce((s,b)=>s+(Number(b.valor_total)||0),0):current?.valor_total; const demand=mode==='anual'?Math.max(...yearBills.map(b=>Number(b.demanda_kw)||0),0):(current?.demanda_kw??null)
 const kwhs=months.map(x=>x.kwh).filter(v=>v!=null); const avg=kwhs.length?kwhs.reduce((a,b)=>a+b,0)/kwhs.length:0; const performance=mode==='mensal'&&totalKwh!=null&&avg?((Number(totalKwh)-avg)/avg)*100:null; const chart=months.map(x=>({...x,label:monthLabel(x.mes),media:avg||null}))
 return <div className="space-y-5">
  <section className="flex flex-col md:flex-row md:items-end md:justify-between gap-4"><div><div className="label text-[#ed1c2e]">Visão geral</div><h1 className="text-3xl font-black mt-1">Dashboard de Energia UPE</h1><p className="text-slate-500 mt-2">Acompanhe consumo, demanda, gastos e tendências em uma única visão.</p></div><button className="btn-primary" onClick={onAdd}><Plus size={18}/>Adicionar conta</button></section>
  <section className="card p-4 flex flex-wrap items-center gap-3"><div className="flex rounded-xl border border-slate-200 p-1"><button className={`px-4 py-2 rounded-lg text-sm font-extrabold ${mode==='mensal'?'bg-[#123b73] text-white':'text-slate-500'}`} onClick={()=>setMode('mensal')}>Mensal</button><button className={`px-4 py-2 rounded-lg text-sm font-extrabold ${mode==='anual'?'bg-[#123b73] text-white':'text-slate-500'}`} onClick={()=>setMode('anual')}>Anual</button></div><select className="field !w-auto" value={year} onChange={e=>setYear(e.target.value)}>{(years.length?years:[year]).map(y=><option key={y}>{y}</option>)}</select>{mode==='mensal'&&<select className="field !w-auto" value={month} onChange={e=>setMonth(e.target.value)}>{months.map(x=><option value={x.mes} key={x.mes}>{monthLong(x.mes)}</option>)}</select>}<span className="text-xs text-slate-400 ml-auto flex items-center gap-1"><CalendarDays size={14}/>Filtros aplicados ao período</span></section>
  {!bills.length?<section className="card p-10 text-center"><img src="/upe-logo.png" className="w-40 mx-auto opacity-90"/><h2 className="text-xl font-extrabold mt-5">Nenhuma conta analisada ainda</h2><p className="text-slate-500 mt-2">Envie a primeira fatura para o Nemotron montar o dashboard.</p><button className="btn-red mt-5" onClick={onAdd}>Enviar primeira conta</button></section>:<>
  <section className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">
   <Kpi icon={Zap} title="Consumo total" value={`${num(totalKwh)} kWh`} note={mode==='anual'?`Acumulado de ${year}`:monthLong(current?.mes_referencia)} />
   <Kpi icon={Gauge} title="Demanda" value={demand?`${num(demand,1)} kW`:'Não disponível'} note={demand?'Maior/medida no período':'A fatura não informa demanda'} />
   <Kpi icon={Wallet} title="Gastos" value={brl(totalValue)} note={mode==='anual'?'Total faturado no ano':current?.concessionaria||'Conta selecionada'} />
   <Kpi icon={performance!=null&&performance>0?TrendingUp:TrendingDown} title="Desempenho" value={performance==null?'—':`${Math.abs(performance).toFixed(1)}%`} note={performance==null?'Sem base de comparação':performance>0?'Acima da média histórica':'Abaixo da média histórica'} tone={performance!=null&&performance>0?'red':'green'} />
  </section>
  <section className="grid xl:grid-cols-3 gap-5"><div className="card p-5 xl:col-span-2"><div className="flex items-center justify-between"><div><div className="label">Consumo mensal</div><h3 className="font-extrabold text-lg mt-1">Consumo x média histórica</h3></div><span className="badge bg-blue-50 text-[#123b73]"><Target size={14}/>Média {num(avg)} kWh</span></div><div className="h-[310px] mt-4"><ResponsiveContainer><AreaChart data={chart}><defs><linearGradient id="fillKwh" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#123b73" stopOpacity={.25}/><stop offset="100%" stopColor="#123b73" stopOpacity={.02}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label"/><YAxis/><Tooltip/><Area type="monotone" dataKey="kwh" stroke="#123b73" strokeWidth={3} fill="url(#fillKwh)"/><Line type="monotone" dataKey="media" stroke="#ed1c2e" strokeDasharray="6 6" dot={false}/></AreaChart></ResponsiveContainer></div></div>
   <div className="card p-5"><div className="label">Leitura Rápida</div><h3 className="font-extrabold text-lg mt-1">Situação do período</h3><div className="mt-5 space-y-3"><Info label="Média de consumo" value={`${num(avg)} kWh`}/><Info label="Meses no histórico" value={String(months.length)}/><Info label="Demanda contratada" value={current?.demanda_contratada_kw?`${num(current.demanda_contratada_kw,1)} kW`:'Não informada'}/><Info label="Confiança da IA" value={current?.confianca?.geral||'—'} /></div></div>
  </section>
  <section className="card p-5"><div className="label">Relação técnica</div><h3 className="font-extrabold text-lg mt-1">Consumo (kWh) x Demanda (kW)</h3><p className="text-sm text-slate-500 mt-1">As grandezas são apresentadas separadamente para evitar conclusões incorretas.</p><div className="h-[320px] mt-4"><ResponsiveContainer><ComposedChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label"/><YAxis yAxisId="left"/><YAxis yAxisId="right" orientation="right"/><Tooltip/><Legend/><Bar yAxisId="left" dataKey="kwh" name="Consumo (kWh)" fill="#123b73" radius={[6,6,0,0]}/><Line yAxisId="right" dataKey="demanda" name="Demanda (kW)" stroke="#ed1c2e" strokeWidth={3} connectNulls={false}/></ComposedChart></ResponsiveContainer></div></section></>}
 </div>
}
function Kpi({icon:Icon,title,value,note,tone}){return <div className="kpi"><div className="flex items-center justify-between"><span className="label">{title}</span><div className={`h-9 w-9 rounded-xl flex items-center justify-center ${tone==='red'?'bg-red-50 text-[#ed1c2e]':tone==='green'?'bg-emerald-50 text-emerald-700':'bg-blue-50 text-[#123b73]'}`}><Icon size={18}/></div></div><div className="value mt-5">{value}</div><div className="text-xs text-slate-500 mt-2">{note}</div></div>}
function Info({label,value}){return <div className="rounded-xl bg-slate-50 p-3"><div className="text-xs text-slate-500">{label}</div><div className="font-extrabold mt-1 capitalize">{value}</div></div>}
