import { useMemo, useState } from 'react'
import { Download, FileJson, FileText, History, Search, Trash2 } from 'lucide-react'
import { brl, num, monthLong, isoToBr } from '../utils/format'

export default function HistoryPage({bills,onDelete}){
 const [q,setQ]=useState('')
 const filtered=useMemo(()=>bills.filter(b=>`${b.concessionaria||''} ${b.unidade_consumidora||''} ${b.mes_referencia||''} ${b.source_file||''}`.toLowerCase().includes(q.toLowerCase())),[bills,q])
 function exportJson(){download(`upe-energia-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(bills,null,2),'application/json')}
 function exportCsv(){const rows=[['referencia','concessionaria','unidade_consumidora','consumo_kwh','demanda_kw','demanda_contratada_kw','valor_total','dias_faturados','vencimento'],...bills.map(b=>[b.mes_referencia,b.concessionaria,b.unidade_consumidora,b.consumo_kwh,b.demanda_kw,b.demanda_contratada_kw,b.valor_total,b.dias_faturados,b.data_vencimento])];download('upe-energia-contas.csv',rows.map(r=>r.map(csvCell).join(';')).join('\n'),'text/csv;charset=utf-8')}
 return <div className="space-y-5 page-enter"><section className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-4"><div><div className="label text-[#ed1c2e]">Base local</div><h1 className="text-3xl font-black mt-1">Histórico de contas</h1><p className="text-slate-500 mt-2">Consulte, filtre e exporte os registros confirmados neste navegador.</p></div><div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={exportCsv} disabled={!bills.length}><Download size={16}/>Exportar CSV</button><button className="btn-secondary" onClick={exportJson} disabled={!bills.length}><FileJson size={16}/>Backup JSON</button></div></section>
 <section className="card history-toolbar"><div className="history-search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar por concessionária, UC, mês ou arquivo..."/></div><div className="history-count"><History size={16}/>{filtered.length} de {bills.length} registro(s)</div></section>
 {!bills.length?<div className="card p-12 text-center text-slate-500"><History className="mx-auto mb-3"/>Nenhuma conta salva.</div>:<div className="space-y-3">{filtered.map((b,i)=><article className="history-item animate-enter" style={{animationDelay:`${i*35}ms`}} key={b.id}><div className="history-file"><FileText size={20}/></div><div className="history-main"><div className="history-title">{monthLong(b.mes_referencia)} <span>•</span> {b.concessionaria||'Concessionária não identificada'}</div><div className="history-meta">UC {b.unidade_consumidora||'—'} • {b.source_file||'PDF'} • venc. {isoToBr(b.data_vencimento)}</div></div><div className="history-stats"><Stat label="Consumo" value={`${num(b.consumo_kwh)} kWh`}/><Stat label="Valor" value={brl(b.valor_total)}/><Stat label="Dias" value={b.dias_faturados!=null?`${num(b.dias_faturados)} dias`:'—'}/><Stat label="Demanda" value={b.demanda_kw!=null?`${num(b.demanda_kw,1)} kW`:'—'}/></div><button onClick={()=>onDelete(b.id)} className="history-delete" title="Excluir"><Trash2 size={17}/></button></article>)}</div>}
 </div>
}
function Stat({label,value}){return <div><span>{label}</span><strong>{value}</strong></div>}
function csvCell(v){const s=v==null?'':String(v);return `"${s.replaceAll('"','""')}"`}
function download(name,content,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
