import { useMemo } from 'react'
import { BarChart, Bar, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { AlertTriangle, BarChart3, BrainCircuit, Building2, FileBarChart2, Printer, ShieldCheck, Target, Users, Wallet, Zap } from 'lucide-react'
import { brl, num, monthLong, pct } from '../utils/format'
import { allYearsMetrics, buildAnnualSeries, buildMonthlySeries, coverageStats, monthMetrics, POLI_AREA_M2, POLI_PEOPLE } from '../utils/analytics'

export default function ReportPage({bills}){
 const monthly=useMemo(()=>buildMonthlySeries(bills),[bills]),annual=useMemo(()=>buildAnnualSeries(monthly),[monthly]),all=allYearsMetrics(monthly,annual),coverage=coverageStats(monthly,bills)
 const alerts=bills.flatMap(b=>(b.diagnostico?.alertas||[]).map(x=>({text:x,month:b.mes_referencia}))).slice(0,8)
 const actions=[...new Set(bills.flatMap(b=>[...(b.diagnostico?.acoes_prioritarias||[]),...(b.diagnostico?.oportunidades_economia||[])]))].slice(0,10)
 const latest=bills[0],latestMonth=latest?monthly.find(x=>x.mes===latest.mes_referencia):null,latestMetrics=monthMetrics(latestMonth,monthly)
 if(!bills.length)return <div className="card p-12 text-center page-enter"><FileBarChart2 className="mx-auto text-[#123b73]" size={42}/><h2 className="text-2xl font-black mt-4">Relatório ainda indisponível</h2><p className="text-slate-500 mt-2">Cadastre ao menos uma conta para gerar a visão executiva.</p></div>
 const summary=buildSummary(latest,latestMetrics)
 return <div className="space-y-5 page-enter report-page">
  <section className="report-hero"><div><div className="hero-kicker"><FileBarChart2 size={14}/>Relatório executivo</div><h1>Panorama de Gestão Energética — POLI</h1><p>Resumo para apresentação, com indicadores objetivos, cobertura da base e prioridades de ação.</p></div><button className="btn-secondary print-hide" onClick={()=>window.print()}><Printer size={17}/>Imprimir / Salvar PDF</button></section>
  <section className="report-kpis"><ReportKpi icon={Zap} label="Consumo acumulado" value={`${num(all.totalConsumption)} kWh`}/><ReportKpi icon={Wallet} label="Gasto confirmado" value={brl(all.totalSpend)}/><ReportKpi icon={Building2} label="kWh/m² total" value={all.totalConsumption!=null?`${num(all.totalConsumption/POLI_AREA_M2,3)} kWh/m²`:'—'}/><ReportKpi icon={Users} label="kWh per capita total" value={all.totalConsumption!=null?`${num(all.totalConsumption/POLI_PEOPLE,3)} kWh/pessoa`:'—'}/></section>
  <section className="grid xl:grid-cols-[1.35fr_.65fr] gap-5"><div className="card p-5 md:p-6"><div className="label">Comparativo anual</div><h2 className="section-title">Consumo por ano</h2><p className="section-subtitle">Consolida o histórico mensal reconhecido nas faturas.</p><div className="h-[330px] mt-5"><ResponsiveContainer><BarChart data={annual}><CartesianGrid strokeDasharray="4 6" vertical={false}/><XAxis dataKey="year"/><YAxis/><Tooltip formatter={v=>[`${num(v)} kWh`,'Consumo']}/><Bar dataKey="consumo" fill="#123b73" radius={[9,9,0,0]} maxBarSize={58}/></BarChart></ResponsiveContainer></div></div><div className="card p-5 md:p-6"><div className="label text-[#ed1c2e]">Síntese executiva</div><h2 className="section-title">Situação mais recente</h2><div className="report-latest"><span>{monthLong(latest.mes_referencia)}</span><strong>{num(latest.consumo_faturado_kwh??latest.consumo_kwh)} kWh</strong><em>{brl(latest.valor_total)}</em></div><p className="text-sm text-slate-600 leading-relaxed mt-4">{summary}</p><div className="report-quality mt-5"><div><span>Consumo</span><strong>{coverage.consumptionMonths} meses</strong></div><div><span>Financeiro</span><strong>{coverage.valueMonths} meses</strong></div><div><span>Demanda</span><strong>{coverage.demandMonths} meses</strong></div></div></div></section>
  <section className="grid lg:grid-cols-2 gap-5"><div className="card p-5 md:p-6"><div className="flex items-center gap-3"><div className="report-section-icon red"><AlertTriangle size={18}/></div><div><div className="label">Riscos e alertas</div><h2 className="section-title !mt-0">Pontos que merecem verificação</h2></div></div><div className="report-list mt-5">{alerts.length?alerts.map((a,i)=><div key={i}><span>{i+1}</span><p>{a.text}<small>{a.month?monthLong(a.month):''}</small></p></div>):<div><span>✓</span><p>Nenhum alerta específico foi registrado nas análises salvas.</p></div>}</div></div><div className="card p-5 md:p-6"><div className="flex items-center gap-3"><div className="report-section-icon green"><Target size={18}/></div><div><div className="label">Plano de ação</div><h2 className="section-title !mt-0">Prioridades sugeridas</h2></div></div><div className="report-list green mt-5">{actions.length?actions.map((a,i)=><div key={i}><span>{i+1}</span><p>{a}</p></div>):<div><span>1</span><p>Amplie a base mensal e estabeleça metas por unidade, setor e período.</p></div>}</div></div></section>
  <section className="report-disclaimer"><BrainCircuit size={18}/><div><strong>Como interpretar este relatório</strong><p>Os números do painel vêm das contas confirmadas e do histórico extraído dos PDFs. As recomendações automáticas são apoio à decisão e devem ser validadas com medições, contratos, tarifas e inspeções em campo.</p></div></section>
 </div>
}
function buildSummary(latest,m){const c=latest?.consumo_faturado_kwh??latest?.consumo_kwh;if(!m||m.historyDeviation==null)return `A conta mais recente registra ${num(c)} kWh. A base histórica ainda é insuficiente para classificar o consumo em relação à média.`;if(m.historyDeviation>0)return `A conta mais recente registra ${num(c)} kWh, ${pct(m.historyDeviation)} acima da média histórica calculada. Há excesso teórico de ${num(m.theoreticalSavingKwh)} kWh sobre essa referência.`;if(m.historyDeviation<0)return `A conta mais recente registra ${num(c)} kWh, ${pct(m.historyDeviation)} abaixo da média histórica calculada. Não há excesso teórico calculável sobre a média.`;return `A conta mais recente registra ${num(c)} kWh, alinhada à média histórica calculada. Não há excesso teórico calculável.`}
function ReportKpi({icon:Icon,label,value}){return <div className="report-kpi"><div><Icon size={19}/></div><span>{label}</span><strong>{value}</strong></div>}
